name = "Turtledove Mod Pack"
author = "eristocrates"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54267d6e8e177f7a4ad140a9115fc73b00d2c41e1c932fe9f18a3e601feb8589"

[versions]
minecraft = "1.20.1"
neoforge = "1.20.1-47.1.106"
