name = "Turtledove Mod Pack"
author = "eristocrates"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11a42335abfc226fe41f06d4eb0f347f550f92173145aea43281377f806b75a7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
no-internal-hashes = true
