
["Loot Tables Rarity Config"]
	common_lt_name = ["mob_loot_bags:lootbags/common"]
	uncommon_lt_name = ["mob_loot_bags:un_common"]
	rare_lt_name = ["mob_loot_bags:lootbags/rare"]
	epic_lt_name = ["mob_loot_bags:lootbags/epic"]
	legendary_lt_name = ["mob_loot_bags:legendary_loot_table"]
	summoning_lt_name = "mob_loot_bags:summoning_loot_table"
	locked_lt_name = "mob_loot_bags:locked_loot_table"
	#if you didn't setup any loot table this is the default one
	default_lt_name = "minecraft:chests/end_city_treasure"

["Loot Bags Drop Rate Config"]
	common_drop_rate = 60.0
	uncommon_drop_rate = 25.0
	rare_drop_rate = 10.0
	epic_drop_rate = 4.0
	legendary_drop_rate = 1.0
	cursed_drop_rate = 1.0
	#this is calculated after the calculation of the rare lootbag drop rate
	timed_drop_rate = 20.0
	drop_chance_overall = 80.0

["Events Config"]
	#enables cursed lootbag drops
	enable_cursed_bag = true
	enable_sound = true
	lucky_list = ["summon minecraft:warden ~ ~ ~", "/place structure minecraft:ancient_city", "weather thunder", "tp @p ~ ~-40 ~", "/effect give @p minecraft:blindness 10", "summon minecraft:tnt ~ ~ ~ {Fuse:40}", "summon minecraft:wither ~ ~ ~", "summon minecraft:zombie ~ ~ ~ {IsBaby:1}", "summon minecraft:firework_rocket ~ ~ ~ {Life:20,LifeTime:40}", "xp add @p 50", "xp add @p 100", "xp add @p 500", "place structure minecraft:village_plains", "place structure minecraft:village_desert  ", "place structure minecraft:ruined_portal  ", "place structure minecraft:pillager_outpost  ", "place structure minecraft:jungle_temple  "]

["Bag Recycler Settings"]
	common_lb = 10.0
	uncommon_lb = 20.0
	rare_lb = 40.0
	epic_lb = 80.0
	legendary_lb = 200.0
	cursed_lb = 60.0
	timed_lb = 40.0
	enchanted_timed_lb = 200.0
	locked_lb = 40.0
	summoning_lb = 40.0

